const MUTATE_PLAYER_POSITION = 'MUTATE_PLAYER_POSITION';
const ADD_BLIP = 'ADD_BLIP';
const REMOVE_BLIP = 'REMOVE_BLIP';
const SET_IS_EXPANDED_IN = 'SET_IS_EXPANDED_IN';
const UPDATE_PLAYER_POSITION = 'UPDATE_PLAYER_POSITION';
const UPDATE_HEADING = 'UPDATE_HEADING';
const UPDATE_PLAYER_STAMINA = 'UPDATE_PLAYER_STAMINA';
const UPDATE_PLAYER_HEALTH = 'UPDATE_PLAYER_HEALTH';
export {
    MUTATE_PLAYER_POSITION,
    UPDATE_PLAYER_POSITION,
    ADD_BLIP,
    REMOVE_BLIP,
    SET_IS_EXPANDED_IN,
    UPDATE_HEADING,
    UPDATE_PLAYER_STAMINA,
    UPDATE_PLAYER_HEALTH,
};
